
# Task Definitions
from agent import researcher,use_case_generator,writer
from crewai import Task
# Task 1: Industry Research
industry_research_task = Task(
    description="Conduct comprehensive market research for {company}. "
                "understand the industry and segment the {company} is working in and Identify the company’s key offerings and strategic focus areas "
                " A vision and product information on the industry should be fine as well."
                 "Analyse Competitors to the {company}"
                  "Understand where the company can improve with respect to competitors",
    expected_output="A report summarizing key findings, competitor analysis, industry benchmarks, and technological trends."
                     "Annual reports of competetor should also be analysed "
                     "Gather all the relavent links",
    agent=researcher,
)


# Task 2: AI Use Case Generation
use_case_task = Task(
    description="Based on market research,analyze industry trends and standards within the {company}’s sector related to AI, ML, and automation."
                 "Propose Creative  use cases where the {company} can leverage GenAI, LLMs, and ML technologies to improve their processes, enhance customer satisfaction, and boost operational efficiency."
                 "Ensure to add references through which certain use cases were suggested"
                 "Collect the above use cases generated and search for relevant datasets on platforms like Kaggle, HuggingFace, and GitHub.",
    expected_output="A detailed document listing creative AI/ML use cases with feasibility assessments and potential datasets."
                    "Should add dataset link from google,huggingface,GitHub and kaggle or any other source"
                    "Resource Asset links should be clickable.",
    agent=use_case_generator,
)

# Task 3: Write Market Research Report
write_report_task = Task(
    description="Use the Content Generated by the researcher and use_case_generator"
    "Write a comprehensive market research report including industry analysis, competitor benchmarks, proposed AI/ML/GEN AI use cases, and strategic recommendations."
    "Highligth the relevant use cases where the {company} can leverage GenAI, LLMs, and ML technologies to improve their processes, enhance customer satisfaction, and boost operational efficiency."
    "Each section should provide actionable insights and measurable outcomes.",
    expected_output="A professional report covering in-depth market research, competitor analysis,AI/ML/GEN AI use cases, and actionable recommendations. Include data visualizations and references."
    "The report should be well detailed and should be covering all the usecases."
    "Add relavent links for annual report and usecase dataset form platfroms like github,huggingface and kaggle",
    agent=writer,
)
